name: 'Auto Commit and Push'
description: 'Auto Commit and Push Action helps to stage all changes and push them to Remote Repo. '

branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  NAME:
    description: 'Your Name'
    required: true
    default: ${{ github.actor }}
  EMAIL:
    description: 'Your Email'
    required: true
    default: ${{ github.actor }}@users.noreply.github.com
  MESSAGE:
    description: 'Commit message'
    required: false
    default: 'Auto Commit by Actions'
  BRANCH:
    description: 'Target branch'
    required: true
    default: ${{ github.head_ref }}
  GITHUB_TOKEN:
    description: 'GitHub token to push changes'
    required: true
    default: ${{ github.token }}
  CO_AUTHORS:
    description: 'Co-authors (comma-separated)'
    required: false
  push_options:
    description: Push options (eg. --force)
    required: false
    default: ''
  commit_options:
    description: Commit options (eg. --no-verify)
    required: false
    default: ''
  add_options:
    description: Add options (eg. -u)
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
