name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '**'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-commit-push"
      description: "Automatically Commit and Push Changes to Your Repository"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}