name: CI / Test

on: 
  push: 
    branches: ["master"]
  workflow_dispatch:

jobs:
   tests:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats
        uses: offensive-vk/auto-stats@v6
        with:
          branch: master
          message: Updated Repository Statistics
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Changes
        run: |
          echo "" >> Test.md
          echo "> [!TIP] " >> Test.md
          echo "> ## Testing Local Action " >> Test.md
          echo "## Workflow Name: ${{ github.workflow }} " >> Test.md
          echo "## Actor: ${{ github.actor }} " >> Test.md
          echo "## Commit SHA: ${{ github.sha }} " >> Test.md

      - name: Commit and Push
        uses: ./
        with: 
          branch: ${{ github.ref_name }}
          message: "Update Automated Stats (Push)"
          github-token: ${{ secrets.GITHUB_TOKEN }}