name: CI / Test

on: 
  push: 
    branches: ["master"]
  workflow_dispatch:

jobs:
   tests:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - uses: actions/checkout@v4

      - name: Make Changes
        run: |
          echo "" >> Test.md
          echo "## Workflow Name: ${{ github.workflow }} " >> Test.md
          echo "## Actor: ${{ github.actor }} " >> Test.md
          echo "## Commit SHA: ${{ github.sha }} " >> Test.md

      - name: Commit and Push
        uses: ./
        with: 
          branch: "master"
          message: "Automated Stats. (Push)"
          github-token: ${{ secrets.GITHUB_TOKEN }}